export const HELLOWORD = 'HELLOWORD'; 
export const APPLICATIONADD = 'APPLICATIONADD'; //增加
export const APPLICATIONDEL = 'APPLICATIONDEL';
export const OPENDIALOG = 'OPENDIALOG';
export const CLOSEDIALOG = 'CLOSEDIALOG';
export const FLUSHAPPLICATION = 'FLUSHAPPLICATION';
export const OPENDELETE = 'OPENDELETE';
export const CLOSEDELETE = 'CLOSEDELETE';
